name: Deploy Develop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Deploy to Heroku
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ secrets.HEROKU_EMAIL }}
          echo ${HEROKU_AUTH} > ~/.netrc
          heroku git:remote --app ${{ secrets.HEROKU_SPLIT_BILL_DEVELOP_NAME }}
          git subtree push --prefix split-bill-api heroku HEAD:master
        env:
          HEROKU_AUTH: ${{ secrets.HEROKU_AUTH }}